# Generated by Django 4.0.5 on 2022-06-10 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='ip',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='availableplatforms',
            unique_together={('game_details', 'platform')},
        ),
        migrations.AlterUniqueTogether(
            name='gamedetails',
            unique_together={('game', 'store')},
        ),
        migrations.AlterUniqueTogether(
            name='images',
            unique_together={('game_details', 'url')},
        ),
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('game', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='videos',
            unique_together={('game_details', 'url')},
        ),
        migrations.AlterUniqueTogether(
            name='visits',
            unique_together={('game', 'ip', 'created_at')},
        ),
    ]
