# Generated by Django 4.0.5 on 2022-06-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_store_url_gamedetails_game_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetails',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
